//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginActivity.DecryptionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeTypeDecrypt", Namespace="http://schemas.datacontract.org/2004/07/WebService.Service")]
    [System.SerializableAttribute()]
    public partial class CompositeTypeDecrypt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DecryptedFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDecryptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ReportFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DecryptedFile {
            get {
                return this.DecryptedFileField;
            }
            set {
                if ((object.ReferenceEquals(this.DecryptedFileField, value) != true)) {
                    this.DecryptedFileField = value;
                    this.RaisePropertyChanged("DecryptedFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDecrypted {
            get {
                return this.IsDecryptedField;
            }
            set {
                if ((this.IsDecryptedField.Equals(value) != true)) {
                    this.IsDecryptedField = value;
                    this.RaisePropertyChanged("IsDecrypted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ReportFile {
            get {
                return this.ReportFileField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportFileField, value) != true)) {
                    this.ReportFileField = value;
                    this.RaisePropertyChanged("ReportFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DecryptionService.IDecryption")]
    public interface IDecryption {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryption/Decrypt", ReplyAction="http://tempuri.org/IDecryption/DecryptResponse")]
        LoginActivity.DecryptionService.CompositeTypeDecrypt Decrypt(string tokenUser, string tokenApi, byte[][] files);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryption/Decrypt", ReplyAction="http://tempuri.org/IDecryption/DecryptResponse")]
        System.Threading.Tasks.Task<LoginActivity.DecryptionService.CompositeTypeDecrypt> DecryptAsync(string tokenUser, string tokenApi, byte[][] files);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDecryptionChannel : LoginActivity.DecryptionService.IDecryption, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DecryptionClient : System.ServiceModel.ClientBase<LoginActivity.DecryptionService.IDecryption>, LoginActivity.DecryptionService.IDecryption {
        
        public DecryptionClient() {
        }
        
        public DecryptionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DecryptionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LoginActivity.DecryptionService.CompositeTypeDecrypt Decrypt(string tokenUser, string tokenApi, byte[][] files) {
            return base.Channel.Decrypt(tokenUser, tokenApi, files);
        }
        
        public System.Threading.Tasks.Task<LoginActivity.DecryptionService.CompositeTypeDecrypt> DecryptAsync(string tokenUser, string tokenApi, byte[][] files) {
            return base.Channel.DecryptAsync(tokenUser, tokenApi, files);
        }
    }
}
