//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginActivity.InformationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InformationService.IInformation")]
    public interface IInformation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformation/GetCurrentUsers", ReplyAction="http://tempuri.org/IInformation/GetCurrentUsersResponse")]
        System.Collections.Generic.List<string> GetCurrentUsers(string tokenUser, string tokenApi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformation/GetCurrentUsers", ReplyAction="http://tempuri.org/IInformation/GetCurrentUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetCurrentUsersAsync(string tokenUser, string tokenApi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInformationChannel : LoginActivity.InformationService.IInformation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InformationClient : System.ServiceModel.ClientBase<LoginActivity.InformationService.IInformation>, LoginActivity.InformationService.IInformation {
        
        public InformationClient() {
        }
        
        public InformationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InformationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> GetCurrentUsers(string tokenUser, string tokenApi) {
            return base.Channel.GetCurrentUsers(tokenUser, tokenApi);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetCurrentUsersAsync(string tokenUser, string tokenApi) {
            return base.Channel.GetCurrentUsersAsync(tokenUser, tokenApi);
        }
    }
}
