//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.WsGenJava {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsgen.gen.com/", ConfigurationName="WsGenJava.wsGen")]
    public interface wsGen {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://wsgen.gen.com/wsGen/receive")]
        void receive();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://wsgen.gen.com/wsGen/receive")]
        System.Threading.Tasks.Task receiveAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://wsgen.gen.com/wsGen/send")]
        void send();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://wsgen.gen.com/wsGen/send")]
        System.Threading.Tasks.Task sendAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsGenChannel : WebService.WsGenJava.wsGen, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsGenClient : System.ServiceModel.ClientBase<WebService.WsGenJava.wsGen>, WebService.WsGenJava.wsGen {
        
        public wsGenClient() {
        }
        
        public wsGenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsGenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsGenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsGenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void receive() {
            base.Channel.receive();
        }
        
        public System.Threading.Tasks.Task receiveAsync() {
            return base.Channel.receiveAsync();
        }
        
        public void send() {
            base.Channel.send();
        }
        
        public System.Threading.Tasks.Task sendAsync() {
            return base.Channel.sendAsync();
        }
    }
}
